<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testframeowrk"
    nsURI="http://www.niu.name/guita/testframework/1.0" nsPrefix="TF">
  <eClassifiers xsi:type="ecore:EClass" name="Statement">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsVariable" eType="#//UIVariableBase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instruction" eType="#//UserInstructionEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIVariableBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name:EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value:EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserInstructionEnum">
    <eLiterals name="SetUIValue">
      <eAnnotations source="EAnnotation0"/>
    </eLiterals>
    <eLiterals name="SendUITrigger" value="1"/>
    <eLiterals name="ManipulateUIControl" value="2"/>
    <eLiterals name="AssertUIValue" value="3"/>
    <eLiterals name="AssertUIState" value="4"/>
    <eLiterals name="InstantiateUISUT" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eOperations name="start"/>
    <eOperations name="stop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsStatement" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsUISUT" eType="#//UISUTVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name:EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eOperations name="start"/>
    <eOperations name="stop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsTestCase" upperBound="-1"
        eType="#//TestCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UISUTVariable" eSuperTypes="#//UIVariableBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itsVariable" upperBound="-1"
        eType="#//UIVariableBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIVisualizedVariable" eSuperTypes="#//UIVariableBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestManager"/>
</ecore:EPackage>
